function [channel,interferenceTransmitter,toRxAng,spLoss] = helperMIMOEnvSetup(gc,tp)
% This function helperMIMOEnvSetup is only in support of
% MIMOBeamformingExample. It may be removed in a future release.

% Copyright 2012-2016 The MathWorks, Inc.



% Calculate relative positions and angles
txPosition = [0;0;0]; 
mobilePosition = tp.mobileRange*[cosd(tp.mobileAngle);sind(tp.mobileAngle);0];
interfPos = tp.interfRange*[cosd(tp.interfAngle);sind(tp.interfAngle);0];
[toRxRange,toRxAng] = rangeangle([txPosition interfPos],mobilePosition);
spLoss =  fspl(toRxRange,gc.lambda); % spreading loss 

% MIMO Fading channel
channel = comm.MIMOChannel(...
    'SampleRate', gc.chanSRate, ...
    'MaximumDopplerShift', gc.Doppler, ...
    'PathDelays', gc.PathDelays,...
    'AveragePathGains', gc.PathGains,...
    'TransmitCorrelationMatrix', eye(tp.numTXElements),...
    'ReceiveCorrelationMatrix', 1,...
    'PathGainsOutputPort', true,...
    'NormalizePathGains', true,...
    'NormalizeChannelOutputs', true);

 % Interference amplifier
 interferenceTransmitter = phased.Transmitter('PeakPower',tp.interfPower,'Gain',tp.interfGain);
