function [collector,receiver,demodulatorOFDM,descrambler,decoder] = ...
        helperMIMORxSetup(gc,tp,numDataSymbols)
% This function helperMIMORxSetup is only in support of
% MIMOBeamformingExample. It may be removed in a future release.

% Copyright 2012-2019 The MathWorks, Inc.

 collector = phased.Collector(...
     'Sensor',phased.IsotropicAntennaElement, ...
     'PropagationSpeed',gc.cLight,...
     'OperatingFrequency',gc.fc);
 
 receiver = phased.ReceiverPreamp( ...
     'Gain',tp.rxGain, ...
     'ReferenceTemperature',gc.nT, ...
     'SampleRate',gc.symRate*gc.upSample);

 demodulatorOFDM = comm.OFDMDemodulator(...
     'FFTLength' ,                      gc.FFTLength,...
     'NumGuardBandCarriers', gc.NumGuardBandCarriers,...
     'RemoveDCCarrier',           true, ...
     'PilotOutputPort',           true, ...
     'PilotCarrierIndices',        gc.PilotCarrierIndices,...
     'CyclicPrefixLength',         gc.CyclicPrefixLength,...
     'NumSymbols',                  numDataSymbols);
 
 descrambler = comm.Descrambler(2, [1 0 1 1 0 1 0 1], [1 1 1 1 1 1 0]);
 
 decoder = comm.ViterbiDecoder( 'InputFormat','Hard', ...
     'TrellisStructure',  poly2trellis(7, [133 171 165]), ...
     'TerminationMethod',  'Terminated', 'OutputDataType','double');
